### ISSUE TITLE
Gateway timed out when training model 

### ISSUE THREAD

**Issue by abuvaneswari** [dlunion/DBFace#48]
Hi,

I created the dataset for training by downloading WIDERFACE images and labels and putting them under 'webface' directory. And I tried training as follows:

$ python train/small/train-small-H-keep12-ignoresmall.py
Downloading: "http://zifuture.com:1000/fs/public_models/mbv3small-09ace125.pth" to /home/tfs/.cache/torch/hub/checkpoints/mbv3small-09ace125.pth
Traceback (most recent call last):
  File "train/small/train-small-H-keep12-ignoresmall.py", line 276, in <module>
    app = App("webface/train/label.txt", "webface/WIDER_train/images")
  File "train/small/train-small-H-keep12-ignoresmall.py", line 166, in __init__
    self.model.init_weights()
  File "/nas4/tfs/COVID-19/DBFace/train/small/dbface.py", line 242, in init_weights
    self.bb.load_pretrain()
  File "/nas4/tfs/COVID-19/DBFace/train/small/dbface.py", line 89, in load_pretrain
    checkpoint = model_zoo.load_url(f"{_MODEL_URL_DOMAIN}/{_MODEL_URL_SMALL}")
  File "/home/tfs/venv_dbface_nni/lib64/python3.6/site-packages/torch/hub.py", line 481, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/tfs/venv_dbface_nni/lib64/python3.6/site-packages/torch/hub.py", line 379, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout

Can you please make the model mbv3small-09ace125.pth available at an accessible location, which we can download and make use of during training?

**Comment by lovejing0306** [comment]
I meet the same issue.

Could you solve it ?

**Comment by RiceZ** [comment]
author has been updated：http://zifuture.com:1556

**Comment by lovejing0306** [comment]
> author has been updated：http://zifuture.com:1556

thanks
